export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'

export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS'
export const UPDATE_COMMENTS = 'UPDATE_COMMENTS'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const ADD_COMMENT = 'ADD_COMMENT'

export const RECEIVE_POST = 'RECEIVE_POST'
export const VOTE_POST_DETAIL = 'VOTE_POST_DETAIL'

export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const RECEIVE_CATEGORY_POSTS = 'RECEIVE_CATEGORY_POSTS'
export const DELETE_POST = 'DELETE_POST'
export const SORT_POSTS = 'SORT_POSTS'
export const VOTE_POST = 'VOTE_POST'
export const CREATE_POST = 'CREATE_POST'
export const UPDATE_POST = 'UPDATE_POST'

export const RECEIVE_COMMENT = 'RECEIVE_COMMENT'
